apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: banking-app
data:
  DATABASE_URL: "postgresql://banking_user:secure_password_123@postgres:5432/banking_db"
  REDIS_URL: "redis://redis:6379/0"
  JWT_SECRET: "super-secret-jwt-key-for-banking-app-2024"
  ENVIRONMENT: "development"
  LOG_LEVEL: "INFO"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-backend
  namespace: banking-app
  labels:
    app: banking-backend
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: banking-backend
  template:
    metadata:
      labels:
        app: banking-backend
        tier: backend
    spec:
      containers:
        - name: banking-backend
          image: banking-backend:latest
          imagePullPolicy: Never # Use local image in Minikube
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: JWT_SECRET
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: ENVIRONMENT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: LOG_LEVEL
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /ping
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: banking-backend
  namespace: banking-app
  labels:
    app: banking-backend
    tier: backend
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: banking-backend
  type: ClusterIP
