apiVersion: v1
kind: Namespace
metadata:
  name: banking-app
  labels:
    name: banking-app
    environment: development
    project: banking-k8s-infrastructure
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: banking-quota
  namespace: banking-app
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 8Gi
    persistentvolumeclaims: "10"
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: banking-limits
  namespace: banking-app
spec:
  limits:
    - type: Container
      default:
        memory: "512Mi"
        cpu: "500m"
      defaultRequest:
        memory: "256Mi"
        cpu: "100m"
      max:
        memory: "1Gi"
        cpu: "1000m"
      min:
        memory: "64Mi"
        cpu: "50m"
